import 'package:flutter/material.dart';
import 'package:flutter_two/model/menu.dart';
import 'package:flutter_two/utils/CustomIcon.dart';
import 'package:flutter_two/utils/uidata.dart';

class MenuViewModel {
  List<Menu> menuItems;

  MenuViewModel({this.menuItems});

  getMenuItems() {
    return menuItems = <Menu>[
      Menu(
        title: "AlertDialog",
        menuColor: Color(0xffc8c4bd),
        icon: CustomIcon.flutter,
        image: UIData.flutterImage,
        items: [],
        nav: "AlertDialogDemo",
        des: "一个小部件，设计警报对话框。",
        relativeUrls: [
          "https://api.flutter.dev/flutter/material/AlertDialog-class.html",
        ],
      ),
      Menu(
        title: "Align",
        menuColor: Color(0xffc8c4bd),
        icon: CustomIcon.flutter,
        image: UIData.flutterImage,
        items: [],
        nav: "AlignDemo",
        des: "一个小部件，它在其内部对齐其子级，并可以根据子级的大小自行调整其大小。",
        relativeUrls: [
          "https://api.flutter.dev/flutter/widgets/Align-class.html",
        ],
      ),
      Menu(
        title: "AnimatedAlign",
        menuColor: Color(0xffc8c4bd),
        icon: CustomIcon.flutter,
        image: UIData.flutterImage,
        items: [],
        nav: "AnimatedAlignDemo",
        des: "Align的动画版本，只要给定的对齐方式发生变化，它就会在给定的持续时间内自动转换孩子的位置。",
        relativeUrls: [
          "https://api.flutter.dev/flutter/widgets/AnimatedAlign-class.html",
        ],
      ),
      Menu(
        title: "AnimatedBuilder",
        menuColor: Color(0xffc8c4bd),
        icon: CustomIcon.flutter,
        image: UIData.flutterImage,
        items: [],
        nav: "AnimatedBuilderDemo",
        des: "用于构建动画的通用小部件。",
        relativeUrls: [
          "https://api.flutter.dev/flutter/widgets/AnimatedBuilder-class.html",
        ],
      ),
      Menu(
        title: "AnimatedContainer",
        menuColor: Color(0xffc8c4bd),
        icon: CustomIcon.flutter,
        image: UIData.flutterImage,
        items: [],
        nav: "AnimatedContainerDemo",
        des: "在一段时间内逐渐改变其值的容器。",
        relativeUrls: [
          "https://api.flutter.dev/flutter/widgets/AnimatedContainer-class.html",
        ],
      ),
      Menu(
        title: "AnimatedCrossFade",
        menuColor: Color(0xffc8c4bd),
        icon: CustomIcon.flutter,
        image: UIData.flutterImage,
        items: [],
        nav: "AnimatedCrossFadeDemo",
        des: "在两个给定子项之间淡入淡出并在其大小之间进行动画处理的小部件。",
        relativeUrls: [
          "https://api.flutter.dev/flutter/widgets/AnimatedCrossFade-class.html",
        ],
      ),
      Menu(
        title: "AnimatedDefaultTextStyle",
        menuColor: Color(0xffc8c4bd),
        icon: CustomIcon.flutter,
        image: UIData.flutterImage,
        items: [],
        nav: "AnimatedDefaultTextStyleDemo",
        des:
            "DefaultTextStyle的动画版本，只要给定样式发生更改，它就会在给定持续时间内自动转换默认文本样式（该文本样式将应用于没有显式样式的后代Text小部件）。",
        relativeUrls: [
          "https://api.flutter.dev/flutter/widgets/AnimatedDefaultTextStyle-class.html",
        ],
      ),
      Menu(
        title: "AnimatedList",
        menuColor: Color(0xffc8c4bd),
        icon: CustomIcon.flutter,
        image: UIData.flutterImage,
        items: [],
        nav: "AnimatedListDemo",
        des: "一个滚动的容器，用于在插入或删除项目时对其进行动画处理。",
        relativeUrls: [
          "https://api.flutter.dev/flutter/widgets/AnimatedList-class.html",
        ],
      ),
      Menu(
        title: "AnimatedOpacity",
        menuColor: Color(0xffc8c4bd),
        icon: CustomIcon.flutter,
        image: UIData.flutterImage,
        items: [],
        nav: "AnimatedOpacityDemo",
        des: "不透明度的动画版本，只要给定的不透明度发生变化，它就会在给定的时间内自动转换孩子的不透明度。",
        relativeUrls: [
          "https://api.flutter.dev/flutter/widgets/AnimatedOpacity-class.html",
        ],
      ),
      Menu(
        title: "AnimatedPadding",
        menuColor: Color(0xffc8c4bd),
        icon: CustomIcon.flutter,
        image: UIData.flutterImage,
        items: [],
        nav: "AnimatedPaddingDemo",
        des: "动画版本的填充，可在给定的时间变化时自动在指定的持续时间内转换压痕。",
        relativeUrls: [
          "https://api.flutter.dev/flutter/widgets/AnimatedPadding-class.html",
        ],
      ),
      Menu(
        title: "AnimatedPhysicalModel",
        menuColor: Color(0xffc8c4bd),
        icon: CustomIcon.flutter,
        image: UIData.flutterImage,
        items: [],
        nav: "AnimatedPhysicalModelDemo",
        des: "物理模型的动画版本。",
        relativeUrls: [
          "https://api.flutter.dev/flutter/widgets/AnimatedPhysicalModel-class.html",
        ],
      ),
      Menu(
        title: "AnimatedPositioned",
        menuColor: Color(0xffc8c4bd),
        icon: CustomIcon.flutter,
        image: UIData.flutterImage,
        items: [],
        nav: "AnimatedPositionedDemo",
        des: "定位的动画版本，只要给定位置发生变化，它就会在给定时间内自动转换孩子的位置。",
        relativeUrls: [
          "https://api.flutter.dev/flutter/widgets/AnimatedPositioned-class.html",
        ],
      ),
      Menu(
        title: "AnimatedSize",
        menuColor: Color(0xffc8c4bd),
        icon: CustomIcon.flutter,
        image: UIData.flutterImage,
        items: [],
        nav: "AnimatedSizeDemo",
        des: "动画小部件，只要给定孩子的尺寸发生变化，它就会在给定时间内自动转换其尺寸。",
        relativeUrls: [
          "https://api.flutter.dev/flutter/widgets/AnimatedSize-class.html",
        ],
      ),
      Menu(
        title: "AnimatedSwitcher",
        menuColor: Color(0xffc8c4bd),
        icon: CustomIcon.flutter,
        image: UIData.flutterImage,
        items: [],
        nav: "AnimatedSwitcherDemo",
        des:
            "默认情况下，一个小部件在新小部件与先前在AnimatedSwitcher上设置为子级的小部件之间执行FadeTransition。",
        relativeUrls: [
          "https://api.flutter.dev/flutter/widgets/AnimatedSwitcher-class.html",
        ],
      ),
      Menu(
        title: "AppBar",
        menuColor: Color(0xffc8c4bd),
        icon: CustomIcon.flutter,
        image: UIData.flutterImage,
        items: [],
        nav: "AppBarDemo",
        des: "一个小部件，设计应用栏。",
        relativeUrls: [
          "https://api.flutter.dev/flutter/material/AppBar-class.html",
        ],
      ),
      Menu(
        title: "AspectRatio",
        menuColor: Color(0xffc8c4bd),
        icon: CustomIcon.flutter,
        image: UIData.flutterImage,
        items: [],
        nav: "AspectRatioDemo",
        des: "尝试将孩子的尺寸调整为特定宽高比的小部件。",
        relativeUrls: [
          "https://api.flutter.dev/flutter/widgets/AspectRatio-class.html",
        ],
      ),
      Menu(
        title: "BackdropFilter",
        menuColor: Color(0xffc8c4bd),
        icon: CustomIcon.flutter,
        image: UIData.flutterImage,
        items: [],
        nav: "BackdropFilterDemo",
        des: "将过滤器应用于现有绘画内容然后绘画子级的小部件。",
        relativeUrls: [
          "https://api.flutter.dev/flutter/widgets/BackdropFilter-class.html",
        ],
      ),
      Menu(
        title: "Banner",
        menuColor: Color(0xffc8c4bd),
        icon: CustomIcon.flutter,
        image: UIData.flutterImage,
        items: [],
        nav: "BannerDemo",
        des: "在另一个小部件的角上方显示对角线消息。",
        relativeUrls: [
          "https://api.flutter.dev/flutter/widgets/Banner-class.html",
        ],
      ),
      Menu(
        title: "Baseline",
        menuColor: Color(0xffc8c4bd),
        icon: CustomIcon.flutter,
        image: UIData.flutterImage,
        items: [],
        nav: "BaselineDemo",
        des: "一个根据孩子的基线放置其孩子的小部件。",
        relativeUrls: [
          "https://api.flutter.dev/flutter/widgets/Baseline-class.html",
        ],
      ),
      Menu(
        title: "BottomAppBar",
        menuColor: Color(0xffc8c4bd),
        icon: CustomIcon.flutter,
        image: UIData.flutterImage,
        items: [],
        nav: "BottomAppBarDemo",
        des:
            "通常与Scaffold.bottomNavigationBar一起使用的容器，并且在顶部可以有一个凹口，以便为重叠的FloatingActionButton留出空间。",
        relativeUrls: [
          "https://api.flutter.dev/flutter/material/BottomAppBar-class.html",
        ],
      ),
      Menu(
        title: "BottomNavigationBar",
        menuColor: Color(0xffc8c4bd),
        icon: CustomIcon.flutter,
        image: UIData.flutterImage,
        items: [],
        nav: "BottomNavigationBarDemo",
        des: "显示在应用程序底部的材质小部件，用于在少量视图（通常在三到五个之间）中选择。",
        relativeUrls: [
          "https://api.flutter.dev/flutter/material/BottomNavigationBar-class.html",
        ],
      ),
      Menu(
        title: "BottomSheet",
        menuColor: Color(0xffc8c4bd),
        icon: CustomIcon.flutter,
        image: UIData.flutterImage,
        items: [],
        nav: "BottomSheetDemo",
        des: "一个小部件，设计底页。",
        relativeUrls: [
          "https://api.flutter.dev/flutter/material/BottomSheet-class.html",
        ],
      ),
      Menu(
        title: "ButtonBar",
        menuColor: Color(0xffc8c4bd),
        icon: CustomIcon.flutter,
        image: UIData.flutterImage,
        items: [],
        nav: "ButtonBarDemo",
        des: "行尾对齐的按钮。",
        relativeUrls: [
          "https://api.flutter.dev/flutter/material/ButtonBar-class.html",
        ],
      ),
      Menu(
        title: "Card",
        menuColor: Color(0xffc8c4bd),
        icon: CustomIcon.flutter,
        image: UIData.flutterImage,
        items: [],
        nav: "CardDemo",
        des: "一个小部件，设计卡。",
        relativeUrls: [
          "https://api.flutter.dev/flutter/material/Card-class.html",
        ],
      ),
      Menu(
        title: "Center",
        menuColor: Color(0xffc8c4bd),
        icon: CustomIcon.flutter,
        image: UIData.flutterImage,
        items: [],
        nav: "CenterDemo",
        des: "在其内部居中放置其子项的小部件。",
        relativeUrls: [
          "https://api.flutter.dev/flutter/material/Center-class.html",
        ],
      ),
      Menu(
        title: "Checkbox",
        menuColor: Color(0xffc8c4bd),
        icon: CustomIcon.flutter,
        image: UIData.flutterImage,
        items: [],
        nav: "CheckboxDemo",
        des: "一个小部件，设计复选框。",
        relativeUrls: [
          "https://api.flutter.dev/flutter/material/Checkbox-class.html",
        ],
      ),
      Menu(
        title: "CheckboxListTile",
        menuColor: Color(0xffc8c4bd),
        icon: CustomIcon.flutter,
        image: UIData.flutterImage,
        items: [],
        nav: "CheckboxListTileDemo",
        des: "带有复选框的ListTile。",
        relativeUrls: [
          "https://api.flutter.dev/flutter/material/SliceCheckboxListTile-class.html",
        ],
      ),
      Menu(
        title: "Chip",
        menuColor: Color(0xffc8c4bd),
        icon: CustomIcon.flutter,
        image: UIData.flutterImage,
        items: [],
        nav: "ChipDemo",
        des: "材一个小部件，设计芯片。",
        relativeUrls: [
          "https://api.flutter.dev/flutter/material/Chip-class.html",
        ],
      ),
      Menu(
        title: "CircleAvatar",
        menuColor: Color(0xffc8c4bd),
        icon: CustomIcon.flutter,
        image: UIData.flutterImage,
        items: [],
        nav: "CircleAvatarDemo",
        des: "代表用户的圆圈。",
        relativeUrls: [
          "https://api.flutter.dev/flutter/material/CircleAvatar-class.html",
        ],
      ),
      Menu(
        title: "CircularProgressIndicator",
        menuColor: Color(0xffc8c4bd),
        icon: CustomIcon.flutter,
        image: UIData.flutterImage,
        items: [],
        nav: "CircularProgressIndicatorDemo",
        des: "一个小部件，设计循环进度指示器，该指示器旋转以指示应用程序正忙。",
        relativeUrls: [
          "https://api.flutter.dev/flutter/material/CircularProgressIndicator-class.html",
        ],
      ),
      Menu(
        title: "ClipOval",
        menuColor: Color(0xffc8c4bd),
        icon: CustomIcon.flutter,
        image: UIData.flutterImage,
        items: [],
        nav: "ClipOvalDemo",
        des: "一个使用椭圆形修剪其子项的小部件。",
        relativeUrls: [
          "https://api.flutter.dev/flutter/widgets/ClipOval-class.html",
        ],
      ),
      Menu(
        title: "ClipPath",
        menuColor: Color(0xffc8c4bd),
        icon: CustomIcon.flutter,
        image: UIData.flutterImage,
        items: [],
        nav: "ClipPathDemo",
        des: "使用路径剪切其子项的小部件。",
        relativeUrls: [
          "https://api.flutter.dev/flutter/widgets/ClipPath-class.html",
        ],
      ),
      Menu(
        title: "ClipRRect",
        menuColor: Color(0xffc8c4bd),
        icon: CustomIcon.flutter,
        image: UIData.flutterImage,
        items: [],
        nav: "ClipRRectDemo",
        des: "使用圆角矩形裁剪其子项的小部件。",
        relativeUrls: [
          "https://api.flutter.dev/flutter/widgets/ClipRRect-class.html",
        ],
      ),
      Menu(
        title: "ClipRect",
        menuColor: Color(0xffc8c4bd),
        icon: CustomIcon.flutter,
        image: UIData.flutterImage,
        items: [],
        nav: "ClipRectDemo",
        des: "一个使用矩形裁剪其子项的小部件。",
        relativeUrls: [
          "https://api.flutter.dev/flutter/widgets/ClipRect-class.html",
        ],
      ),
      Menu(
        title: "Column",
        menuColor: Color(0xffc8c4bd),
        icon: CustomIcon.flutter,
        image: UIData.flutterImage,
        items: [],
        nav: "ColumnDemo",
        des: "以垂直数组显示其子级的小部件。",
        relativeUrls: [
          "https://api.flutter.dev/flutter/material/Column-class.html",
        ],
      ),
      Menu(
        title: "ConstrainedBox",
        menuColor: Color(0xffc8c4bd),
        icon: CustomIcon.flutter,
        image: UIData.flutterImage,
        items: [],
        nav: "ConstrainedBoxDemo",
        des: "在其子项上施加其他约束的窗口小部件。",
        relativeUrls: [
          "https://api.flutter.dev/flutter/widgets/ConstrainedBox-class.html",
        ],
      ),
      Menu(
        title: "Container",
        menuColor: Color(0xffc8c4bd),
        icon: CustomIcon.flutter,
        image: UIData.flutterImage,
        items: [],
        nav: "ContainerDemo",
        des: "一个方便的小部件，它结合了常见的绘画，定位和大小调整小部件。",
        relativeUrls: [
          "https://api.flutter.dev/flutter/material/Container-class.html",
        ],
      ),
      Menu(
        title: "CupertinoActionSheet",
        menuColor: Color(0xffc8c4bd),
        icon: CustomIcon.flutter,
        image: UIData.flutterImage,
        items: [],
        nav: "CupertinoActionSheetDemo",
        des: "一个方便的小部件，它结合了常见的绘画，定位和大小调整小部件。",
        relativeUrls: [
          "https://api.flutter.dev/flutter/cupertino/CupertinoActionSheet-class.html",
        ],
      ),
      Menu(
        title: "CupertinoActivityIndicator",
        menuColor: Color(0xffc8c4bd),
        icon: CustomIcon.flutter,
        image: UIData.flutterImage,
        items: [],
        nav: "CupertinoActivityIndicatorDemo",
        des: "iOS风格的活动指示器。",
        relativeUrls: [
          "https://api.flutter.dev/flutter/cupertino/CupertinoActivityIndicator-class.html",
        ],
      ),
      Menu(
        title: "CupertinoAlertDialog",
        menuColor: Color(0xffc8c4bd),
        icon: CustomIcon.flutter,
        image: UIData.flutterImage,
        items: [],
        nav: "CupertinoAlertDialogDemo",
        des: "iOS样式的警报对话框。",
        relativeUrls: [
          "https://api.flutter.dev/flutter/cupertino/CupertinoAlertDialog-class.html",
        ],
      ),
      Menu(
        title: "CupertinoButton",
        menuColor: Color(0xffc8c4bd),
        icon: CustomIcon.flutter,
        image: UIData.flutterImage,
        items: [],
        nav: "CupertinoButtonDemo",
        des: "iOS样式的按钮。",
        relativeUrls: [
          "https://api.flutter.dev/flutter/cupertino/CupertinoButton-class.html",
        ],
      ),
      Menu(
        title: "CupertinoContextMenu",
        menuColor: Color(0xffc8c4bd),
        icon: CustomIcon.flutter,
        image: UIData.flutterImage,
        items: [],
        nav: "CupertinoContextMenuDemo",
        des: "当孩子长按时打开的全屏模式路线。",
        relativeUrls: [
          "https://api.flutter.dev/flutter/cupertino/CupertinoContextMenu-class.html",
        ],
      ),
      Menu(
        title: "CupertinoDatePicker",
        menuColor: Color(0xffc8c4bd),
        icon: CustomIcon.flutter,
        image: UIData.flutterImage,
        items: [],
        nav: "CupertinoDatePickerDemo",
        des: "iOS风格的日期选择器小部件。",
        relativeUrls: [
          "https://api.flutter.dev/flutter/cupertino/CupertinoDatePicker-class.html",
        ],
      ),
      Menu(
        title: "CupertinoNavigationBar",
        menuColor: Color(0xffc8c4bd),
        icon: CustomIcon.flutter,
        image: UIData.flutterImage,
        items: [],
        nav: "CupertinoNavigationBarDemo",
        des: "iOS样式的导航栏。",
        relativeUrls: [
          "https://api.flutter.dev/flutter/cupertino/CupertinoNavigationBar-class.html",
        ],
      ),
      Menu(
        title: "CupertinoPageScaffold",
        menuColor: Color(0xffc8c4bd),
        icon: CustomIcon.flutter,
        image: UIData.flutterImage,
        items: [],
        nav: "CupertinoPageScaffoldDemo",
        des: "实现单个iOS应用程序页面的布局。",
        relativeUrls: [
          "https://api.flutter.dev/flutter/cupertino/CupertinoPageScaffold-class.html",
        ],
      ),
      Menu(
        title: "CupertinoSlider",
        menuColor: Color(0xffc8c4bd),
        icon: CustomIcon.flutter,
        image: UIData.flutterImage,
        items: [],
        nav: "CupertinoSliderDemo",
        des: "iOS样式的滑块。",
        relativeUrls: [
          "https://api.flutter.dev/flutter/cupertino/CupertinoSlider-class.html",
        ],
      ),
      Menu(
        title: "CupertinoSwitch",
        menuColor: Color(0xffc8c4bd),
        icon: CustomIcon.flutter,
        image: UIData.flutterImage,
        items: [],
        nav: "CupertinoSwitchDemo",
        des: "iOS样式的开关。",
        relativeUrls: [
          "https://api.flutter.dev/flutter/cupertino/CupertinoSwitch-class.html",
        ],
      ),
      Menu(
        title: "CupertinoTabBar",
        menuColor: Color(0xffc8c4bd),
        icon: CustomIcon.flutter,
        image: UIData.flutterImage,
        items: [],
        nav: "CupertinoTabBarDemo",
        des: "iOS样式的底部导航标签栏。",
        relativeUrls: [
          "https://api.flutter.dev/flutter/cupertino/CupertinoTabBar-class.html",
        ],
      ),
      Menu(
        title: "CupertinoTimerPicker",
        menuColor: Color(0xffc8c4bd),
        icon: CustomIcon.flutter,
        image: UIData.flutterImage,
        items: [],
        nav: "CupertinoTimerPickerDemo",
        des: "iOS风格的倒数计时器选择器。",
        relativeUrls: [
          "https://api.flutter.dev/flutter/cupertino/CupertinoTimerPicker-class.html",
        ],
      ),
      Menu(
        title: "CustomPaint",
        menuColor: Color(0xffc8c4bd),
        icon: CustomIcon.flutter,
        image: UIData.flutterImage,
        items: [],
        nav: "CustomPaintDemo",
        des: "一个小部件，提供在绘制阶段在其上进行绘制的画布。",
        relativeUrls: [
          "https://api.flutter.dev/flutter/material/CustomPaint-class.html",
        ],
      ),
      Menu(
        title: "CustomScrollView",
        menuColor: Color(0xffc8c4bd),
        icon: CustomIcon.flutter,
        image: UIData.flutterImage,
        items: [],
        nav: "CustomScrollViewDemo",
        des: "ScrollView，可使用条子创建自定义滚动效果。",
        relativeUrls: [
          "https://api.flutter.dev/flutter/widgets/CustomScrollView-class.html",
        ],
      ),
      Menu(
        title: "DataTable",
        menuColor: Color(0xffc8c4bd),
        icon: CustomIcon.flutter,
        image: UIData.flutterImage,
        items: [],
        nav: "DataTableDemo",
        des: "一个小部件，设计数据表。",
        relativeUrls: [
          "https://api.flutter.dev/flutter/material/DataTable-class.html",
        ],
      ),
      Menu(
        title: "DatePicker",
        menuColor: Color(0xffc8c4bd),
        icon: CustomIcon.flutter,
        image: UIData.flutterImage,
        items: [],
        nav: "DatePickerDemo",
        des: "显示一个包含物料设计日期选择器的对话框。",
        relativeUrls: [
          "https://api.flutter.dev/flutter/material/showDatePicker.html",
        ],
      ),
      Menu(
        title: "DecoratedBox",
        menuColor: Color(0xffc8c4bd),
        icon: CustomIcon.flutter,
        image: UIData.flutterImage,
        items: [],
        nav: "DecoratedBoxDemo",
        des: "在子项绘制之前或之后绘制装饰的小部件。",
        relativeUrls: [
          "https://api.flutter.dev/flutter/widgets/DecoratedBox-class.html",
        ],
      ),
      Menu(
        title: "DecoratedBoxTransition",
        menuColor: Color(0xffc8c4bd),
        icon: CustomIcon.flutter,
        image: UIData.flutterImage,
        items: [],
        nav: "DecoratedBoxTransitionDemo",
        des: "DecoratedBox的动画版本，可对其装饰的不同属性进行动画处理。",
        relativeUrls: [
          "https://api.flutter.dev/flutter/widgets/DecoratedBoxTransition-class.html",
        ],
      ),
      Menu(
        title: "DefaultTextStyle",
        menuColor: Color(0xffc8c4bd),
        icon: CustomIcon.flutter,
        image: UIData.flutterImage,
        items: [],
        nav: "DefaultTextStyleDemo",
        des: "适用于没有显式样式的后代Text窗口小部件的文本样式。",
        relativeUrls: [
          "https://api.flutter.dev/flutter/widgets/DefaultTextStyle-class.html",
        ],
      ),
      Menu(
        title: "Dismissible",
        menuColor: Color(0xffc8c4bd),
        icon: CustomIcon.flutter,
        image: UIData.flutterImage,
        items: [],
        nav: "DismissibleDemo",
        des: "可以通过在指示的方向上拖动来关闭小部件。",
        relativeUrls: [
          "https://api.flutter.dev/flutter/widgets/Dismissible-class.html",
        ],
      ),
      Menu(
        title: "Divider",
        menuColor: Color(0xffc8c4bd),
        icon: CustomIcon.flutter,
        image: UIData.flutterImage,
        items: [],
        nav: "DividerDemo",
        des: "一个设备像素粗的水平线，两侧都有填充。",
        relativeUrls: [
          "https://api.flutter.dev/flutter/material/Divider-class.html",
        ],
      ),
      Menu(
        title: "Draggable",
        menuColor: Color(0xffc8c4bd),
        icon: CustomIcon.flutter,
        image: UIData.flutterImage,
        items: [],
        nav: "DraggableDemo",
        des: "空值",
        relativeUrls: [
          "null",
        ],
      ),
      Menu(
        title: "Drawer",
        menuColor: Color(0xffc8c4bd),
        icon: CustomIcon.flutter,
        image: UIData.flutterImage,
        items: [],
        nav: "DrawerDemo",
        des: "一种材料设计面板，可从支架的边缘水平滑入以显示应用程序中的导航链接。",
        relativeUrls: [
          "https://api.flutter.dev/flutter/material/Drawer-class.html",
        ],
      ),
      Menu(
        title: "DropdownButton",
        menuColor: Color(0xffc8c4bd),
        icon: CustomIcon.flutter,
        image: UIData.flutterImage,
        items: [],
        nav: "DropdownButtonDemo",
        des: "用于从项目列表中选择的材料设计按钮。",
        relativeUrls: [
          "https://api.flutter.dev/flutter/material/DropdownButton-class.html",
        ],
      ),
      Menu(
        title: "Expanded",
        menuColor: Color(0xffc8c4bd),
        icon: CustomIcon.flutter,
        image: UIData.flutterImage,
        items: [],
        nav: "ExpandedDemo",
        des: "扩展行，列或Flex子级的小部件，以便该子级填充可用空间。",
        relativeUrls: [
          "https://api.flutter.dev/flutter/widgets/Expanded-class.html",
        ],
      ),
      Menu(
        title: "ExpansionPanelList",
        menuColor: Color(0xffc8c4bd),
        icon: CustomIcon.flutter,
        image: UIData.flutterImage,
        items: [],
        nav: "ExpansionPanelListDemo",
        des: "一个小部件，展开面板列表，其中列出了其子元素并为展开添加动画效果。",
        relativeUrls: [
          "https://api.flutter.dev/flutter/material/ExpansionPanelList-class.html",
        ],
      ),
      Menu(
        title: "FlatButton",
        menuColor: Color(0xffc8c4bd),
        icon: CustomIcon.flutter,
        image: UIData.flutterImage,
        items: [],
        nav: "FlatButtonDemo",
        des: "一个小部件，设计平面按钮。",
        relativeUrls: [
          "https://api.flutter.dev/flutter/material/FlatButton-class.html",
        ],
      ),
      Menu(
        title: "Flexible",
        menuColor: Color(0xffc8c4bd),
        icon: CustomIcon.flutter,
        image: UIData.flutterImage,
        items: [],
        nav: "FlexibleDemo",
        des: "控制行，列或Flex的子代如何弯曲的小部件。",
        relativeUrls: [
          "https://api.flutter.dev/flutter/widgets/Flexible-class.html",
        ],
      ),
      Menu(
        title: "FloatingActionButton",
        menuColor: Color(0xffc8c4bd),
        icon: CustomIcon.flutter,
        image: UIData.flutterImage,
        items: [],
        nav: "FloatingActionButtonDemo",
        des: "一个小部件，设计的浮动动作按钮。",
        relativeUrls: [
          "https://api.flutter.dev/flutter/material/FloatingActionButton-class.html",
        ],
      ),
      Menu(
        title: "Flow",
        menuColor: Color(0xffc8c4bd),
        icon: CustomIcon.flutter,
        image: UIData.flutterImage,
        items: [],
        nav: "FlowDemo",
        des: "根据FlowDelegate中的逻辑，可有效调整子元素大小和位置的小部件。",
        relativeUrls: [
          "https://api.flutter.dev/flutter/widgets/Flow-class.html",
        ],
      ),
      Menu(
        title: "FlutterLogo",
        menuColor: Color(0xffc8c4bd),
        icon: CustomIcon.flutter,
        image: UIData.flutterImage,
        items: [],
        nav: "FlutterLogoDemo",
        des: "Flutter徽标，以小部件形式",
        relativeUrls: [
          "https://api.flutter.dev/flutter/material/FlutterLogo-class.html",
        ],
      ),
      Menu(
        title: "Form",
        menuColor: Color(0xffc8c4bd),
        icon: CustomIcon.flutter,
        image: UIData.flutterImage,
        items: [],
        nav: "FormDemo",
        des: "用于将多个表单字段小部件（例如TextField小部件）分组在一起的可选容器。",
        relativeUrls: [
          "https://api.flutter.dev/flutter/widgets/Form-class.html",
        ],
      ),
      Menu(
        title: "GestureDetector",
        menuColor: Color(0xffc8c4bd),
        icon: CustomIcon.flutter,
        image: UIData.flutterImage,
        items: [],
        nav: "GestureDetectorDemo",
        des: "检测手势的小部件。",
        relativeUrls: [
          "https://api.flutter.dev/flutter/widgets/GestureDetector-class.html",
        ],
      ),
      Menu(
        title: "GridView",
        menuColor: Color(0xffc8c4bd),
        icon: CustomIcon.flutter,
        image: UIData.flutterImage,
        items: [],
        nav: "GridViewDemo",
        des: "可滚动的2D小部件数组。",
        relativeUrls: [
          "https://api.flutter.dev/flutter/widgets/GridView-class.html",
        ],
      ),
      Menu(
        title: "Icon",
        menuColor: Color(0xffc8c4bd),
        icon: CustomIcon.flutter,
        image: UIData.flutterImage,
        items: [],
        nav: "IconDemo",
        des: "一个小部件，设计图标。",
        relativeUrls: [
          "https://api.flutter.dev/flutter/material/Icon-class.html",
        ],
      ),
      Menu(
        title: "IconButton",
        menuColor: Color(0xffc8c4bd),
        icon: CustomIcon.flutter,
        image: UIData.flutterImage,
        items: [],
        nav: "IconButtonDemo",
        des: "一个小部件，设计图标按钮。",
        relativeUrls: [
          "https://api.flutter.dev/flutter/material/IconButton-class.html",
        ],
      ),
      Menu(
        title: "Image",
        menuColor: Color(0xffc8c4bd),
        icon: CustomIcon.flutter,
        image: UIData.flutterImage,
        items: [],
        nav: "ImageDemo",
        des: "显示图像的小部件。",
        relativeUrls: [
          "https://api.flutter.dev/flutter/widgets/Image-class.html",
        ],
      ),
      Menu(
        title: "IndexedStack",
        menuColor: Color(0xffc8c4bd),
        icon: CustomIcon.flutter,
        image: UIData.flutterImage,
        items: [],
        nav: "IndexedStackDemo",
        des: "一个堆栈，显示一个孩子列表中的一个孩子。",
        relativeUrls: [
          "https://api.flutter.dev/flutter/widgets/IndexedStack-class.html",
        ],
      ),
      Menu(
        title: "InkWell",
        menuColor: Color(0xffc8c4bd),
        icon: CustomIcon.flutter,
        image: UIData.flutterImage,
        items: [],
        nav: "InkWellDemo",
        des: "响应触摸的材料的矩形区域。",
        relativeUrls: [
          "https://api.flutter.dev/flutter/material/InkWell-class.html",
        ],
      ),
      Menu(
        title: "LinearProgressIndicator",
        menuColor: Color(0xffc8c4bd),
        icon: CustomIcon.flutter,
        image: UIData.flutterImage,
        items: [],
        nav: "LinearProgressIndicatorDemo",
        des: "材料设计线性进度指示器，也称为进度条。",
        relativeUrls: [
          "https://api.flutter.dev/flutter/material/LinearProgressIndicator-class.html",
        ],
      ),
      Menu(
        title: "ListTile",
        menuColor: Color(0xffc8c4bd),
        icon: CustomIcon.flutter,
        image: UIData.flutterImage,
        items: [],
        nav: "ListTileDemo",
        des: "固定高度的单个行，通常包含一些文本以及前导或尾随图标。",
        relativeUrls: [
          "https://api.flutter.dev/flutter/material/ListTile-class.html",
        ],
      ),
      Menu(
        title: "ListView",
        menuColor: Color(0xffc8c4bd),
        icon: CustomIcon.flutter,
        image: UIData.flutterImage,
        items: [],
        nav: "ListViewDemo",
        des: "线性排列的小部件的可滚动列表。",
        relativeUrls: [
          "https://api.flutter.dev/flutter/widgets/ListView-class.html",
        ],
      ),
      Menu(
        title: "NestedScrollView",
        menuColor: Color(0xffc8c4bd),
        icon: CustomIcon.flutter,
        image: UIData.flutterImage,
        items: [],
        nav: "NestedScrollViewDemo",
        des: "可以在其内部的滚动视图中嵌套其他滚动视图，并且其滚动位置是固有链接的。",
        relativeUrls: [
          "https://api.flutter.dev/flutter/widgets/NestedScrollView-class.html",
        ],
      ),
      Menu(
        title: "Opacity",
        menuColor: Color(0xffc8c4bd),
        icon: CustomIcon.flutter,
        image: UIData.flutterImage,
        items: [],
        nav: "OpacityDemo",
        des: "一个小部件，设计的浮动动作按钮。",
        relativeUrls: [
          "https://api.flutter.dev/flutter/widgets/Opacity-class.html",
        ],
      ),
      Menu(
        title: "OutlineButton",
        menuColor: Color(0xffc8c4bd),
        icon: CustomIcon.flutter,
        image: UIData.flutterImage,
        items: [],
        nav: "OutlineButtonDemo",
        des: "类似于带有细灰色圆形矩形边框的FlatButton。",
        relativeUrls: [
          "https://api.flutter.dev/flutter/material/OutlineButton-class.html",
        ],
      ),
      Menu(
        title: "OverflowBox",
        menuColor: Color(0xffc8c4bd),
        icon: CustomIcon.flutter,
        image: UIData.flutterImage,
        items: [],
        nav: "OverflowBoxDemo",
        des: "一个小部件，对其子对象施加的约束与其从其父对象获得的约束不同，这可能会使子对象溢出父对象。",
        relativeUrls: [
          "https://api.flutter.dev/flutter/widgets/OverflowBox-class.html",
        ],
      ),
      Menu(
        title: "Padding",
        menuColor: Color(0xffc8c4bd),
        icon: CustomIcon.flutter,
        image: UIData.flutterImage,
        items: [],
        nav: "PaddingDemo",
        des: "一个小部件，它通过给定的填充来插入其子级。",
        relativeUrls: [
          "https://api.flutter.dev/flutter/widgets/Padding-class.html",
        ],
      ),
      Menu(
        title: "PageView",
        menuColor: Color(0xffc8c4bd),
        icon: CustomIcon.flutter,
        image: UIData.flutterImage,
        items: [],
        nav: "PageViewDemo",
        des: "可滚动的列表，逐页工作。",
        relativeUrls: [
          "https://api.flutter.dev/flutter/widgets/PageView-class.html",
        ],
      ),
      Menu(
        title: "PhysicalModel",
        menuColor: Color(0xffc8c4bd),
        icon: CustomIcon.flutter,
        image: UIData.flutterImage,
        items: [],
        nav: "PhysicalModelDemo",
        des: "代表物理层的小部件，将其子代裁剪为形状。",
        relativeUrls: [
          "https://api.flutter.dev/flutter/widgets/PhysicalModel-class.html",
        ],
      ),
      Menu(
        title: "Placeholder",
        menuColor: Color(0xffc8c4bd),
        icon: CustomIcon.flutter,
        image: UIData.flutterImage,
        items: [],
        nav: "PlaceholderDemo",
        des: "一个小部件，它绘制一个框，该框表示有一天其他小部件将添加到何处。",
        relativeUrls: [
          "https://api.flutter.dev/flutter/widgets/Placeholder-class.html",
        ],
      ),
      Menu(
        title: "PopupMenuButton",
        menuColor: Color(0xffc8c4bd),
        icon: CustomIcon.flutter,
        image: UIData.flutterImage,
        items: [],
        nav: "PopupMenuButtonDemo",
        des: "按下时显示菜单，并因为选择了某个项目而将其关闭，则调用onSelected。",
        relativeUrls: [
          "https://api.flutter.dev/flutter/material/PopupMenuButton-class.html",
        ],
      ),
      Menu(
        title: "Positioned",
        menuColor: Color(0xffc8c4bd),
        icon: CustomIcon.flutter,
        image: UIData.flutterImage,
        items: [],
        nav: "PositionedDemo",
        des: "一个控件，用于控制Stack的子元素放置的位置。",
        relativeUrls: [
          "https://api.flutter.dev/flutter/widgets/Positioned-class.html",
        ],
      ),
      Menu(
        title: "PositionedTransition",
        menuColor: Color(0xffc8c4bd),
        icon: CustomIcon.flutter,
        image: UIData.flutterImage,
        items: [],
        nav: "PositionedTransitionDemo",
        des:
            "定位的动画版本，需要使用特定的AnimationRelativeRect动画，以在动画的整个生命周期中将孩子的位置从开始位置过渡到结束位置。",
        relativeUrls: [
          "https://api.flutter.dev/flutter/widgets/PositionedTransition-class.html",
        ],
      ),
      Menu(
        title: "Radio",
        menuColor: Color(0xffc8c4bd),
        icon: CustomIcon.flutter,
        image: UIData.flutterImage,
        items: [],
        nav: "RadioDemo",
        des: "一个小部件，设计单选按钮。",
        relativeUrls: [
          "https://api.flutter.dev/flutter/material/Radio-class.html",
        ],
      ),
      Menu(
        title: "RadioListTile",
        menuColor: Color(0xffc8c4bd),
        icon: CustomIcon.flutter,
        image: UIData.flutterImage,
        items: [],
        nav: "RadioListTileDemo",
        des: "带收音机的ListTile。",
        relativeUrls: [
          "https://api.flutter.dev/flutter/material/RadioListTile-class.html",
        ],
      ),
      Menu(
        title: "RaisedButton",
        menuColor: Color(0xffc8c4bd),
        icon: CustomIcon.flutter,
        image: UIData.flutterImage,
        items: [],
        nav: "RaisedButtonDemo",
        des: "一个小部件，设计的凸起按钮。",
        relativeUrls: [
          "https://api.flutter.dev/flutter/material/RaisedButton-class.html",
        ],
      ),
      Menu(
        title: "RangeSlider",
        menuColor: Color(0xffc8c4bd),
        icon: CustomIcon.flutter,
        image: UIData.flutterImage,
        items: [],
        nav: "RangeSliderDemo",
        des: "一个小部件，设计范围滑块。",
        relativeUrls: [
          "https://api.flutter.dev/flutter/material/RangeSlider-class.html",
        ],
      ),
      Menu(
        title: "RefreshIndicator",
        menuColor: Color(0xffc8c4bd),
        icon: CustomIcon.flutter,
        image: UIData.flutterImage,
        items: [],
        nav: "RefreshIndicatorDemo",
        des: "一个小组件，支持“材质滑动”以刷新惯用语。",
        relativeUrls: [
          "https://api.flutter.dev/flutter/material/RefreshIndicator-class.html",
        ],
      ),
      Menu(
        title: "RichText",
        menuColor: Color(0xffc8c4bd),
        icon: CustomIcon.flutter,
        image: UIData.flutterImage,
        items: [],
        nav: "RichTextDemo",
        des: "一段富文本。",
        relativeUrls: [
          "https://api.flutter.dev/flutter/material/RichText-class.html",
        ],
      ),
      Menu(
        title: "RotatedBox",
        menuColor: Color(0xffc8c4bd),
        icon: CustomIcon.flutter,
        image: UIData.flutterImage,
        items: [],
        nav: "RotatedBoxDemo",
        des: "将其子级旋转整数倍的小部件。",
        relativeUrls: [
          "https://api.flutter.dev/flutter/widgets/RotatedBox-class.html",
        ],
      ),
      Menu(
        title: "RotationTransition",
        menuColor: Color(0xffc8c4bd),
        icon: CustomIcon.flutter,
        image: UIData.flutterImage,
        items: [],
        nav: "RotationTransitionDemo",
        des: "对小部件的旋转进行动画处理。",
        relativeUrls: [
          "https://api.flutter.dev/flutter/widgets/RotationTransition-class.html",
        ],
      ),
      Menu(
        title: "Row",
        menuColor: Color(0xffc8c4bd),
        icon: CustomIcon.flutter,
        image: UIData.flutterImage,
        items: [],
        nav: "RowDemo",
        des: "以水平阵列显示其子级的小部件。",
        relativeUrls: [
          "https://api.flutter.dev/flutter/material/Row-class.html",
        ],
      ),
      Menu(
        title: "Scaffold",
        menuColor: Color(0xffc8c4bd),
        icon: CustomIcon.flutter,
        image: UIData.flutterImage,
        items: [],
        nav: "ScaffoldDemo",
        des: "实现基本的材料设计视觉布局结构。",
        relativeUrls: [
          "https://api.flutter.dev/flutter/material/Scaffold-class.html",
        ],
      ),
      Menu(
        title: "Scrollbar",
        menuColor: Color(0xffc8c4bd),
        icon: CustomIcon.flutter,
        image: UIData.flutterImage,
        items: [],
        nav: "ScrollbarDemo",
        des: "一个小部件，设计滚动条。",
        relativeUrls: [
          "https://api.flutter.dev/flutter/material/Scrollbar-class.html",
        ],
      ),
      Menu(
        title: "SelectableText",
        menuColor: Color(0xffc8c4bd),
        icon: CustomIcon.flutter,
        image: UIData.flutterImage,
        items: [],
        nav: "SelectableTextDemo",
        des: "具有单一样式的可选文本。",
        relativeUrls: [
          "https://api.flutter.dev/flutter/material/SelectableText-class.html",
        ],
      ),
      Menu(
        title: "SimpleDialog",
        menuColor: Color(0xffc8c4bd),
        icon: CustomIcon.flutter,
        image: UIData.flutterImage,
        items: [],
        nav: "SimpleDialogDemo",
        des: "一个简单的材料设计对话框。",
        relativeUrls: [
          "https://api.flutter.dev/flutter/material/SimpleDialog-class.html",
        ],
      ),
      Menu(
        title: "SingleChildScrollView",
        menuColor: Color(0xffc8c4bd),
        icon: CustomIcon.flutter,
        image: UIData.flutterImage,
        items: [],
        nav: "SingleChildScrollViewDemo",
        des: "一个可以在其中滚动小部件的框。",
        relativeUrls: [
          "https://api.flutter.dev/flutter/widgets/SingleChildScrollView-class.html",
        ],
      ),
      Menu(
        title: "SizedBox",
        menuColor: Color(0xffc8c4bd),
        icon: CustomIcon.flutter,
        image: UIData.flutterImage,
        items: [],
        nav: "SizedBoxDemo",
        des: "具有指定大小的盒子。",
        relativeUrls: [
          "https://api.flutter.dev/flutter/widgets/SizedBox-class.html",
        ],
      ),
      Menu(
        title: "SizedOverflowBox",
        menuColor: Color(0xffc8c4bd),
        icon: CustomIcon.flutter,
        image: UIData.flutterImage,
        items: [],
        nav: "SizedOverflowBoxDemo",
        des: "具有特定大小但将其原始约束传递给其子代的窗口小部件，子代可能随后溢出。",
        relativeUrls: [
          "https://api.flutter.dev/flutter/widgets/SizedOverflowBox-class.html",
        ],
      ),
      Menu(
        title: "Slider",
        menuColor: Color(0xffc8c4bd),
        icon: CustomIcon.flutter,
        image: UIData.flutterImage,
        items: [],
        nav: "SliderDemo",
        des: "一个小部件，设计滑块。",
        relativeUrls: [
          "https://api.flutter.dev/flutter/material/Slider-class.html",
        ],
      ),
      Menu(
        title: "SliverAppBar",
        menuColor: Color(0xffc8c4bd),
        icon: CustomIcon.flutter,
        image: UIData.flutterImage,
        items: [],
        nav: "SliverAppBarDemo",
        des: "与CustomScrollView集成的材质设计应用栏。",
        relativeUrls: [
          "https://api.flutter.dev/flutter/material/SliverAppBar-class.html",
        ],
      ),
      Menu(
        title: "Stack",
        menuColor: Color(0xffc8c4bd),
        icon: CustomIcon.flutter,
        image: UIData.flutterImage,
        items: [],
        nav: "StackDemo",
        des: "相对于其框的边缘放置其子项的小部件。",
        relativeUrls: [
          "https://api.flutter.dev/flutter/widgets/Stack-class.html",
        ],
      ),
      Menu(
        title: "Stepper",
        menuColor: Color(0xffc8c4bd),
        icon: CustomIcon.flutter,
        image: UIData.flutterImage,
        items: [],
        nav: "StepperDemo",
        des: "一个小部件，步进器小部件，显示一系列步骤的进度。",
        relativeUrls: [
          "https://api.flutter.dev/flutter/material/Stepper-class.html",
        ],
      ),
      Menu(
        title: "Switch",
        menuColor: Color(0xffc8c4bd),
        icon: CustomIcon.flutter,
        image: UIData.flutterImage,
        items: [],
        nav: "SwitchDemo",
        des: "材料设计开关。",
        relativeUrls: [
          "https://api.flutter.dev/flutter/material/Switch-class.html",
        ],
      ),
      Menu(
        title: "TabBar",
        menuColor: Color(0xffc8c4bd),
        icon: CustomIcon.flutter,
        image: UIData.flutterImage,
        items: [],
        nav: "TabBarDemo",
        des: "一个小部件，设计小部件，显示标签的水平行。",
        relativeUrls: [
          "https://api.flutter.dev/flutter/material/TabBar-class.html",
        ],
      ),
      Menu(
        title: "Table",
        menuColor: Color(0xffc8c4bd),
        icon: CustomIcon.flutter,
        image: UIData.flutterImage,
        items: [],
        nav: "TableDemo",
        des: "使用表布局算法为其子级的小部件。",
        relativeUrls: [
          "https://api.flutter.dev/flutter/widgets/Table-class.html",
        ],
      ),
      Menu(
        title: "Text",
        menuColor: Color(0xffc8c4bd),
        icon: CustomIcon.flutter,
        image: UIData.flutterImage,
        items: [],
        nav: "TextDemo",
        des: "单一样式的文字。",
        relativeUrls: [
          "https://api.flutter.dev/flutter/material/Text-class.html",
        ],
      ),
      Menu(
        title: "TextField",
        menuColor: Color(0xffc8c4bd),
        icon: CustomIcon.flutter,
        image: UIData.flutterImage,
        items: [],
        nav: "TextFieldDemo",
        des: "一个小部件，设计文本字段。",
        relativeUrls: [
          "https://api.flutter.dev/flutter/material/TextField-class.html",
        ],
      ),
      Menu(
        title: "TimePicker",
        menuColor: Color(0xffc8c4bd),
        icon: CustomIcon.flutter,
        image: UIData.flutterImage,
        items: [],
        nav: "TimePickerDemo",
        des: "显示一个包含材料设计时间选择器的对话框。",
        relativeUrls: [
          "https://api.flutter.dev/flutter/material/showTimePicker.html",
        ],
      ),
      Menu(
        title: "ToggleButtons",
        menuColor: Color(0xffc8c4bd),
        icon: CustomIcon.flutter,
        image: UIData.flutterImage,
        items: [],
        nav: "ToggleButtonsDemo",
        des: "水平切换按钮集。",
        relativeUrls: [
          "https://api.flutter.dev/flutter/material/ToggleButtons-class.html",
        ],
      ),
      Menu(
        title: "Tooltip",
        menuColor: Color(0xffc8c4bd),
        icon: CustomIcon.flutter,
        image: UIData.flutterImage,
        items: [],
        nav: "TooltipDemo",
        des: "一个小部件，设计工具提示。",
        relativeUrls: [
          "https://api.flutter.dev/flutter/material/Tooltip-class.html",
        ],
      ),
      Menu(
        title: "Transform",
        menuColor: Color(0xffc8c4bd),
        icon: CustomIcon.flutter,
        image: UIData.flutterImage,
        items: [],
        nav: "TransformDemo",
        des: "在绘制子级之前应用转换的小部件。",
        relativeUrls: [
          "https://api.flutter.dev/flutter/widgets/Transform-class.html",
        ],
      ),
      Menu(
        title: "VerticalDivider",
        menuColor: Color(0xffc8c4bd),
        icon: CustomIcon.flutter,
        image: UIData.flutterImage,
        items: [],
        nav: "VerticalDividerDemo",
        des: "一个设备像素的垂直粗线，两侧均带有填充。",
        relativeUrls: [
          "https://api.flutter.dev/flutter/material/VerticalDivider-class.html",
        ],
      ),
      Menu(
        title: "Wrap",
        menuColor: Color(0xffc8c4bd),
        icon: CustomIcon.flutter,
        image: UIData.flutterImage,
        items: [],
        nav: "WrapDemo",
        des: "在多个水平或垂直行中显示其子级的窗口小部件。",
        relativeUrls: [
          "https://api.flutter.dev/flutter/widgets/Wrap-class.html",
        ],
      ),
    ];
  }
}
